global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'distributedlog-brokers'
    static_configs:
      - targets:
          - 'broker-0:9094'
          - 'broker-1:9094'
          - 'broker-2:9094'
        labels:
          cluster: 'distributedlog'
